from typing import List, Dict, Any, TypedDict, Annotated
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    """
    State representing the context of a single chat request in the RAG agent.
    """
    # LangGraph message history with the standard message reducer
    messages: Annotated[List[BaseMessage], add_messages]
    
    # Dynamic domain & RBAC scoping parameters
    scope: str
    role: str
    
    # List of retrieved document chunks matching the scope and role
    retrieved_docs: List[Dict[str, Any]]
    
    # Final answer generated by the LLM
    generation: str

    # Intent classification ('conversational' vs 'domain_query')
    intent: str
